spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  mustache:
    cache: false
  data:
    redis:
      port: 6379
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  autoconfigure:
    exclude:
      - org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiEmbeddingAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiImageAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiAudioSpeechAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiAudioTranscriptionAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiModerationAutoConfiguration
      - org.springframework.ai.model.anthropic.autoconfigure.AnthropicChatAutoConfiguration
      - org.springframework.ai.model.chat.client.autoconfigure.ChatClientAutoConfiguration
      - org.springframework.ai.model.chat.memory.autoconfigure.ChatMemoryAutoConfiguration
      - org.springframework.ai.model.chat.observation.autoconfigure.ChatObservationAutoConfiguration
      - org.springframework.ai.model.embedding.observation.autoconfigure.EmbeddingObservationAutoConfiguration
      - org.springframework.ai.model.image.observation.autoconfigure.ImageObservationAutoConfiguration
      - org.springframework.ai.model.tool.autoconfigure.ToolCallingAutoConfiguration
      - org.springframework.ai.retry.autoconfigure.SpringAiRetryAutoConfiguration

ai:
  model:
    open-ai: gpt-4o-mini                  # Set OpenAI Model : Default is gpt-4o-mini
    anthropic: claude-3-5-sonnet-20241022 # Set Anthropic Model : Default is claude-3-5-sonnet-20241022

loki:
  url: ${LOKI_URL:}
  query-path: ${LOKI_QUERY_PATH:/loki/api/v1/query}

analysis:
  data-retention-hours: 120 # Set the number of hours to retain analysis data : Default is 120 (5 days)
