spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  mustache:
    cache: false
  data:
    redis:
      port: 6379
  autoconfigure:
    exclude:
      - org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiEmbeddingAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiImageAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiAudioSpeechAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiAudioTranscriptionAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiModerationAutoConfiguration
      - org.springframework.ai.model.anthropic.autoconfigure.AnthropicChatAutoConfiguration
      - org.springframework.ai.model.chat.client.autoconfigure.ChatClientAutoConfiguration
      - org.springframework.ai.model.chat.memory.autoconfigure.ChatMemoryAutoConfiguration
      - org.springframework.ai.model.chat.observation.autoconfigure.ChatObservationAutoConfiguration
      - org.springframework.ai.model.embedding.observation.autoconfigure.EmbeddingObservationAutoConfiguration
      - org.springframework.ai.model.image.observation.autoconfigure.ImageObservationAutoConfiguration
      - org.springframework.ai.model.tool.autoconfigure.ToolCallingAutoConfiguration
      - org.springframework.ai.retry.autoconfigure.SpringAiRetryAutoConfiguration

loki:
  url: ${LOKI_URL:}
  query-path: ${LOKI_QUERY_PATH:/loki/api/v1/query}
