package com.walter.spring.ai.ops.controller.dto

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import io.swagger.v3.oas.annotations.media.Schema

@Schema(description = "Top-level Grafana Alerting webhook payload")
@JsonIgnoreProperties(ignoreUnknown = true)
data class GrafanaAlertingRequest(
    @Schema(description = "Grafana contact point receiver name")
    val receiver: String,
    @Schema(description = "Overall alert group status (firing / resolved)", example = "firing")
    val status: String,
    @Schema(description = "Grafana organisation ID")
    val orgId: Long,
    @Schema(description = "List of individual alerts in this notification")
    val alerts: List<GrafanaAlert>,
    @Schema(description = "Labels that are common across all alerts in the group")
    val groupLabels: Map<String, String>,
    @Schema(description = "Labels shared by all alerts in this notification")
    val commonLabels: Map<String, String>,
    @Schema(description = "Annotations shared by all alerts in this notification")
    val commonAnnotations: Map<String, String>,
    @Schema(description = "External URL of the Grafana instance")
    val externalURL: String,
    @Schema(description = "Alertmanager payload version", example = "1")
    val version: String,
    @Schema(description = "Group key that uniquely identifies this alert group")
    val groupKey: String,
    @Schema(description = "Number of alerts truncated due to payload size limits")
    val truncatedAlerts: Int,
    @Schema(description = "Notification title generated by Grafana")
    val title: String,
    @Schema(description = "Alert state string", example = "alerting")
    val state: String,
    @Schema(description = "Notification message generated by Grafana")
    val message: String,
) {
    fun isFiring(): Boolean = status == "firing"
    fun isResolved(): Boolean = status == "resolved"
    fun createAlertSectionPrompt(): String {
        val alert = this.alerts.firstOrNull { it.isFiring() } ?: this.alerts.firstOrNull()
        val request = this
        val alertSection = buildString {
            appendLine("## Alert Information")
            appendLine("- Title: ${request.title}")
            appendLine("- Status: ${request.status}")
            appendLine("- Message: ${request.message}")
            if (alert != null) {
                appendLine("- Alert Name: ${alert.alertName()}")
                appendLine("- Started At: ${alert.startsAt}")
                if (alert.annotations.isNotEmpty()) {
                    appendLine("- Annotations: ${alert.annotations.entries.joinToString { "${it.key}=${it.value}" }}")
                }
                if (alert.labels.isNotEmpty()) {
                    appendLine("- Labels: ${alert.labels.entries.joinToString { "${it.key}=${it.value}" }}")
                }
            }
        }
        return alertSection
    }
}
